# Generated by Django 4.2.24 on 2025-09-30 17:48

from django.db import migrations

def init_initial_quantity(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for p in Product.objects.all():
        if p.initial_quantity == 0:
            p.initial_quantity = p.quantity
            p.save(update_fields=['initial_quantity'])

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_initial_quantity_product_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(init_initial_quantity, migrations.RunPython.noop),
    ]
